name: shabat or
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
     - name: myaction name
       uses: actions/checkout@v3
    
     - name: myjob
       run : echo "hello world"
  
