
name: classroom
on:
  push:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.output.test}}
    steps: 
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id : step2
        run: |
          echo ${{steps.step1.outputs.test}}
          echo ${{steps.step1.outputs.test}"Karush"}

        
  job2: 
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - run: echo ${{job.jobs1.outputs.output1}}
